### PR TITLE
Resolve AttributeError: 'WalletElectrum2' object has no attribute '_passphrase_recovery'

### LINKED ISSUE #192: Doesn't work with Electrum wallet generated on 4.0.9?
How do I use this with the new Electrum seed system? Wallet is encrypted with completely unknown passphrase, unfortunately.

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
Closes #192.

### CODE REVIEW

**Comment by 3rdIteration** [comment]
Thanks for the fix :)
